BEGIN;
UPDATE tp_odberror SET oer_carpartstext='Valve DMTL, Cablage, Calculateur moteur' WHERE oer_code='P1043' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAP, Cablage, Calculateur moteur' WHERE oer_code='P1100' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAP, Durites de depression, Calculateur moteur' WHERE oer_code='P1101' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAP, Durites bouchees ou fuyantes, Vanne EGR, Cablage' WHERE oer_code='P1102' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAP, Durites bouchees ou fuyantes, Vanne EGR, Cablage' WHERE oer_code='P1103' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAF, Filtre a air, Cablage' WHERE oer_code='P1104' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAF, Filtre a air, Conduit d''admission, Cablage' WHERE oer_code='P1105' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAF, Connecteur, Cablage, Calculateur moteur' WHERE oer_code='P1106' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MAF, Connecteur, Cablage, Calculateur moteur' WHERE oer_code='P1107' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a carburant, Relais de pompe, Cablage, Fusible' WHERE oer_code='P1108' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a carburant, Regulateur de pression, Filtre a carburant' WHERE oer_code='P1109' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais de pompe, Systeme ETS, Calculateur moteur' WHERE oer_code='P1110' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur IAT, Connecteur, Cablage, Calculateur moteur' WHERE oer_code='P1111' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur IAT, Connecteur, Cablage, Calculateur moteur' WHERE oer_code='P1112' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression differentielle, Durites, Cablage' WHERE oer_code='P1113' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ECT, Cablage, TCM, Calculateur moteur' WHERE oer_code='P1114' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ECT, Cablage, TCM, Calculateur moteur' WHERE oer_code='P1115' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression de suralimentation, Cablage, Turbocompresseur' WHERE oer_code='P1116' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur du papillon, Corps de papillon, Cablage, Calculateur moteur' WHERE oer_code='P1118' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne de dosage, Cablage, Calculateur moteur' WHERE oer_code='P1119' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur, Cablage, Calculateur moteur' WHERE oer_code='P1120' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur APS, Cablage, Calculateur moteur' WHERE oer_code='P1121' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Turbocompresseur, Soupape de decharge, Solenoide de commande, Calculateur moteur' WHERE oer_code='P1122' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Pression de carburant, Injecteurs, Calculateur moteur' WHERE oer_code='P1123' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Pression de carburant, Fuites d''air, Calculateur moteur' WHERE oer_code='P1124' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression de rampe, Cablage, Calculateur moteur' WHERE oer_code='P1125' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression de rampe secondaire, Cablage, Calculateur moteur' WHERE oer_code='P1126' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Pression de carburant, Injecteurs, Calculateur moteur' WHERE oer_code='P1127' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Pression de carburant, Fuites d''air, Calculateur moteur' WHERE oer_code='P1128' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur de transmission' WHERE oer_code='P1129' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1130' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Resistance d''ajustement, Cablage, Calculateur moteur' WHERE oer_code='P1131' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1132' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1133' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Chauffage de la sonde, Cablage' WHERE oer_code='P1134' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Servo de calage, Cablage, Pompe d''injection' WHERE oer_code='P1135' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Injecteurs, Sonde lambda, Calculateur moteur' WHERE oer_code='P1136' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Capteur MAF, Cablage, Corps de papillon' WHERE oer_code='P1140' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1141' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1144' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1145' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Potentiometre, Cablage, Calculateur moteur' WHERE oer_code='P1146' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur APS, Cablage, Calculateur moteur' WHERE oer_code='P1147' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur barometrique, Cablage, Calculateur moteur' WHERE oer_code='P1150' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur APS, Cablage, Calculateur moteur' WHERE oer_code='P1151' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur APS, Cablage, Calculateur moteur' WHERE oer_code='P1152' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur APS, Cablage, Calculateur moteur' WHERE oer_code='P1153' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Chauffage de la sonde, Cablage' WHERE oer_code='P1154' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve Limp Home, Cablage, Calculateur moteur' WHERE oer_code='P1155' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur d''admission variable, Solenoide, Calculateur moteur' WHERE oer_code='P1159' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe haute pression, Rampe, Cablage, Calculateur moteur' WHERE oer_code='P1162' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Pression de carburant, Fuites d''echappement, Systeme EVAP' WHERE oer_code='P1166' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Pression de carburant, Fuites d''echappement, Systeme EVAP' WHERE oer_code='P1167' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Cablage, Fusible' WHERE oer_code='P1168' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Cablage, Fusible' WHERE oer_code='P1169' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur barometrique, Cablage, Calculateur moteur' WHERE oer_code='P1170' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Moteur ETS, Calculateur moteur' WHERE oer_code='P1171' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur du papillon, Cablage, Calculateur moteur' WHERE oer_code='P1172' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur du papillon, Cablage, Alternateur' WHERE oer_code='P1173' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Moteur ETS, Calculateur moteur' WHERE oer_code='P1174' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Moteur ETS, Calculateur moteur' WHERE oer_code='P1175' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur du papillon, Cablage, Calculateur moteur' WHERE oer_code='P1176' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur du papillon, Cablage, Calculateur moteur' WHERE oer_code='P1177' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais ETS, Cablage, Calculateur moteur' WHERE oer_code='P1178' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Moteur du papillon, Calculateur moteur' WHERE oer_code='P1179' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur de pression, Cablage, Calculateur moteur' WHERE oer_code='P1180' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression de rampe, Pompe a carburant, Regulateur' WHERE oer_code='P1181' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur, Cablage, Calculateur moteur' WHERE oer_code='P1182' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur, Cablage, Calculateur moteur' WHERE oer_code='P1183' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Sonde lambda, Regulateur, Cablage' WHERE oer_code='P1184' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur de pression, Pompe haute pression, Capteur de pression' WHERE oer_code='P1185' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a carburant, Filtre a carburant, Regulateur de pression' WHERE oer_code='P1186' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur de pression, Cablage, Pompe a carburant' WHERE oer_code='P1187' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Injecteurs, Rampe de carburant, Raccords, Regulateur' WHERE oer_code='P1188' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur electronique, Cablage, Calculateur moteur' WHERE oer_code='P1189' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Actionneur, Cablage, Calculateur moteur' WHERE oer_code='P1190' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Calculateur moteur, Systeme ETS' WHERE oer_code='P1191' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Moteur ETS, Calculateur moteur' WHERE oer_code='P1192' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Calculateur moteur' WHERE oer_code='P1193' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, Calculateur moteur' WHERE oer_code='P1194' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur du papillon, Cablage, Calculateur moteur' WHERE oer_code='P1195' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Moteur ETS, Calculateur moteur' WHERE oer_code='P1196' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1221' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais GPL, Pompe a carburant, Cablage' WHERE oer_code='P1229' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1230' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a carburant, Relais, Cablage, Fusible' WHERE oer_code='P1231' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Volet d''air, Actionneur, Cablage' WHERE oer_code='P1235' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de position du volet, Cablage, Calculateur moteur' WHERE oer_code='P1236' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de position du volet, Cablage, Calculateur moteur' WHERE oer_code='P1237' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Injecteurs, Cablage' WHERE oer_code='P1240' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1250' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1252' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve, Cablage, Calculateur moteur' WHERE oer_code='P1290' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Capteur MAF, Capteur MAP, Calculateur moteur' WHERE oer_code='P1295' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CKP, Capteur CMP, Cablage' WHERE oer_code='P1300' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CKP, Roue phonique, Cablage' WHERE oer_code='P1301' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CKP, Cablage, Calculateur moteur' WHERE oer_code='P1302' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CKP, Cablage, Calculateur moteur' WHERE oer_code='P1303' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CMP, Cablage, Calculateur moteur' WHERE oer_code='P1304' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CMP, Roue phonique, Cablage' WHERE oer_code='P1305' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CMP, Cablage, Calculateur moteur' WHERE oer_code='P1306' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur CMP, Capteur d''acceleration, Cablage, Calculateur moteur' WHERE oer_code='P1307' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''acceleration, Cablage, Calculateur moteur' WHERE oer_code='P1308' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''acceleration, Cablage, Calculateur moteur' WHERE oer_code='P1309' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1310' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1311' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Bougie, Cablage' WHERE oer_code='P1312' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1313' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1314' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1315' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Bougie, Cablage' WHERE oer_code='P1316' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1317' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1318' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1319' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Bougie, Cablage' WHERE oer_code='P1320' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1321' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1322' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1323' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais de prechauffage, Bougies de prechauffage, Cablage' WHERE oer_code='P1324' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Bougies de prechauffage, Calculateur moteur' WHERE oer_code='P1325' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais de prechauffage, Cablage, Calculateur moteur' WHERE oer_code='P1326' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Fusible' WHERE oer_code='P1327' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage entre l''outil de programmation, Calculateur moteur' WHERE oer_code='P1330' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1331' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1332' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1333' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1334' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1335' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1336' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1337' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1338' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur moteur' WHERE oer_code='P1340' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1341' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1342' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1343' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1344' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1345' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1346' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1347' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ionique, Bougie, Cablage' WHERE oer_code='P1348' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1351' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1352' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1353' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1354' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1355' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1356' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1357' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Bobine d''allumage, Calculateur moteur' WHERE oer_code='P1358' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse de roue, Roue phonique, Cablage' WHERE oer_code='P1372' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de cliquetis, Cablage, Calculateur moteur' WHERE oer_code='P1386' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Solenoide EGR, Vanne EGR, Calculateur moteur' WHERE oer_code='P1400' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module DMTL, Composants du circuit EVAP' WHERE oer_code='P1401' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur DMTL, Cablage, Calculateur moteur' WHERE oer_code='P1402' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve DMTL, Cablage, Calculateur moteur' WHERE oer_code='P1403' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Chauffage DMTL, Cablage' WHERE oer_code='P1404' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature EGR, Vanne EGR, Cablage' WHERE oer_code='P1405' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur EGT, Vanne EGR, Calculateur moteur' WHERE oer_code='P1406' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a air secondaire, Soupape d''air, Cablage' WHERE oer_code='P1415' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a air secondaire, Soupape, Durites' WHERE oer_code='P1416' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe a air secondaire, Soupape d''air, Cablage' WHERE oer_code='P1418' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Soupape d''air secondaire, Cablage, Calculateur moteur' WHERE oer_code='P1419' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve de purge du canister, Cablage, Calculateur moteur' WHERE oer_code='P1440' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bouchon de reservoir, Durites EVAP, Canister' WHERE oer_code='P1443' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide de purge, Durites, Calculateur moteur' WHERE oer_code='P1457' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Compresseur A/C, Relais, Cablage, Calculateur moteur' WHERE oer_code='P1458' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide EGR, Cablage, Calculateur moteur' WHERE oer_code='P1485' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1486' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1487' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur A/C, Cablage, Calculateur moteur' WHERE oer_code='P1500' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature de batterie, Cablage, Systeme de charge' WHERE oer_code='P1501' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Systeme de charge, Calculateur moteur' WHERE oer_code='P1502' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur de regulateur, Cablage, Calculateur moteur' WHERE oer_code='P1503' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur de regulateur, Contacteur de frein, Cablage' WHERE oer_code='P1504' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne IAC, Cablage, Calculateur moteur' WHERE oer_code='P1505' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne IAC, Cablage, Calculateur moteur' WHERE oer_code='P1506' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne IAC, Cablage, Calculateur moteur' WHERE oer_code='P1507' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne IAC, Cablage, Calculateur moteur' WHERE oer_code='P1508' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur MPS, Cablage, Calculateur moteur' WHERE oer_code='P1509' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne IAC, Cablage, Calculateur moteur' WHERE oer_code='P1510' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne ISC, Cablage, Calculateur moteur' WHERE oer_code='P1511' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur ECT, Cablage, Calculateur moteur' WHERE oer_code='P1512' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne ISC, Cablage, Calculateur moteur' WHERE oer_code='P1513' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature d''huile, Vanne IAC, Cablage' WHERE oer_code='P1515' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature d''huile, Vanne IAC, Cablage' WHERE oer_code='P1516' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature d''huile, Cablage, Calculateur moteur' WHERE oer_code='P1517' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Alternateur, Cablage, Calculateur moteur' WHERE oer_code='P1520' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur/interrupteur de pression de direction, Cablage, Calculateur moteur' WHERE oer_code='P1521' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur moteur' WHERE oer_code='P1522' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Capteur TPS, Calculateur moteur' WHERE oer_code='P1523' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur moteur' WHERE oer_code='P1524' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur APS, Capteur de pression, Cablage' WHERE oer_code='P1525' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit d''alimentation des capteurs, Cablage, Calculateur moteur' WHERE oer_code='P1526' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit d''alimentation des capteurs, Cablage, Calculateur moteur' WHERE oer_code='P1527' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, TCM, Calculateur moteur' WHERE oer_code='P1529' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Capteur de vitesse, Cablage' WHERE oer_code='P1530' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de papillon, Moteur du papillon, Calculateur moteur' WHERE oer_code='P1532' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide VICS, Cablage, Calculateur moteur' WHERE oer_code='P1533' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur IFB, Cablage, Systeme GPL' WHERE oer_code='P1539' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur IFB, Systeme GPL, Cablage' WHERE oer_code='P1540' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Contacteur de frein, Cablage, Calculateur moteur' WHERE oer_code='P1543' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur A/C, Cablage, Relais' WHERE oer_code='P1545' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de cliquetis, Cablage, Calculateur moteur' WHERE oer_code='P1550' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne ISC, Cablage, Calculateur moteur' WHERE oer_code='P1552' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Vanne ISC, Cablage, Calculateur moteur' WHERE oer_code='P1553' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Potentiometre, Cablage, Calculateur moteur' WHERE oer_code='P1555' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de cliquetis, Cablage, Calculateur moteur' WHERE oer_code='P1560' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de batterie, Cablage, Calculateur moteur' WHERE oer_code='P1566' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve de pression, Cablage, Calculateur moteur' WHERE oer_code='P1567' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve de pression, Cablage, Calculateur moteur' WHERE oer_code='P1568' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Valve de pression, Cablage, Calculateur moteur' WHERE oer_code='P1569' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Systeme de freinage, Calculateur moteur' WHERE oer_code='P1572' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur moteur' WHERE oer_code='P1573' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Connecteur, Calculateur moteur' WHERE oer_code='P1586' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, Calculateur moteur' WHERE oer_code='P1587' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide VICS, Cablage, Calculateur moteur' WHERE oer_code='P1593' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, TCM, Calculateur moteur' WHERE oer_code='P1600' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Connecteur de diagnostic, Calculateur moteur' WHERE oer_code='P1601' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, TCM, Calculateur moteur' WHERE oer_code='P1602' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, TCM, Module TCS, Calculateur moteur' WHERE oer_code='P1603' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, TCM, Cablage, Calculateur moteur' WHERE oer_code='P1604' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''acceleration, Calculateur IFB, Cablage' WHERE oer_code='P1605' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Capteur d''acceleration, Cablage' WHERE oer_code='P1606' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur IFB, Systeme ETS, Cablage' WHERE oer_code='P1607' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Systeme ETS, Calculateur moteur' WHERE oer_code='P1608' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module immobiliseur, Cablage, Calculateur moteur' WHERE oer_code='P1609' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Module immobiliseur' WHERE oer_code='P1610' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur moteur' WHERE oer_code='P1611' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Systeme ETS, Cablage' WHERE oer_code='P1613' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Module ETS' WHERE oer_code='P1614' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur moteur' WHERE oer_code='P1615' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais principal, Fusible, Cablage, Calculateur moteur' WHERE oer_code='P1616' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin MIL, Cablage, Calculateur moteur' WHERE oer_code='P1617' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Systeme de gestion moteur, Calculateur moteur' WHERE oer_code='P1618' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais principal, Fusible, Cablage' WHERE oer_code='P1619' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Systeme ETS, Circuit d''admission, Systeme d''echappement, Calculateur moteur' WHERE oer_code='P161B' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais A/C, Cablage, Calculateur moteur' WHERE oer_code='P1620' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Soupape, Relais A/C, Cablage' WHERE oer_code='P1621' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais A/C, Cablage, Calculateur moteur' WHERE oer_code='P1622' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin MIL, Relais de ventilateur, Cablage' WHERE oer_code='P1623' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais de ventilateur, Cablage, Moteur de ventilateur' WHERE oer_code='P1624' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais de ventilateur, Cablage, Moteur de ventilateur' WHERE oer_code='P1625' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin immobiliseur, Cablage, Module immobiliseur' WHERE oer_code='P1626' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Ventilateur, Relais, Cablage' WHERE oer_code='P1627' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Cablage, Calculateur moteur' WHERE oer_code='P1628' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Ventilateur' WHERE oer_code='P1629' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, TCM' WHERE oer_code='P1630' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, Calculateur moteur' WHERE oer_code='P1631' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, Module TCS' WHERE oer_code='P1632' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie, Alternateur, Regulateur de tension, Cablage' WHERE oer_code='P1633' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Chauffage auxiliaire' WHERE oer_code='P1634' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Chauffage' WHERE oer_code='P1635' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Regulateur, Cablage, Injecteurs' WHERE oer_code='P1636' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur' WHERE oer_code='P1638' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur' WHERE oer_code='P1639' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur VIM, Cablage, Calculateur moteur' WHERE oer_code='P1640' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur VIM, Cablage, Calculateur moteur' WHERE oer_code='P1641' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Module BCM' WHERE oer_code='P1642' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit de suralimentation, Injecteurs, Calculateur moteur' WHERE oer_code='P1645' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit de suralimentation, Cablage, Calculateur moteur' WHERE oer_code='P1646' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit de suralimentation, Cablage, Batterie' WHERE oer_code='P1647' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Cablage, Calculateur moteur' WHERE oer_code='P1650' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Contacteur a cle, Cablage, Calculateur moteur' WHERE oer_code='P1652' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Relais principal, Cablage' WHERE oer_code='P1653' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur, Cablage, Calculateur moteur' WHERE oer_code='P1660' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Cablage, Calculateur moteur' WHERE oer_code='P1661' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bobine d''allumage, Cablage, Calculateur moteur' WHERE oer_code='P1665' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Injecteurs, Module de commande d''allumage, Calculateur moteur' WHERE oer_code='P1670' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Injecteurs, Calculateur moteur' WHERE oer_code='P1671' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Ventilateur' WHERE oer_code='P1672' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Ventilateur, Relais, Cablage' WHERE oer_code='P1673' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Ventilateur, Module immobiliseur, Cablage' WHERE oer_code='P1674' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Module immobiliseur' WHERE oer_code='P1675' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Module SMARTRA' WHERE oer_code='P1676' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur moteur' WHERE oer_code='P1677' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur moteur' WHERE oer_code='P1678' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur moteur' WHERE oer_code='P1679' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module immobiliseur, Cle, Calculateur moteur' WHERE oer_code='P1688' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Transpondeur, Module immobiliseur, Calculateur moteur' WHERE oer_code='P1689' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module SMARTRA, Cablage, Module immobiliseur, Calculateur moteur' WHERE oer_code='P1690' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Antenne immobiliseur, Cablage, Module immobiliseur' WHERE oer_code='P1691' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Cablage, Module immobiliseur' WHERE oer_code='P1692' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Transpondeur, Module immobiliseur, TCM, Calculateur moteur' WHERE oer_code='P1693' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module immobiliseur, Cablage, Calculateur moteur' WHERE oer_code='P1694' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Module immobiliseur' WHERE oer_code='P1695' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cle, Transpondeur, Module immobiliseur, Calculateur moteur' WHERE oer_code='P1696' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Outil de diagnostic, Module immobiliseur, Cablage' WHERE oer_code='P1697' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Transpondeur, Module immobiliseur' WHERE oer_code='P1698' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module immobiliseur, Cle, Calculateur moteur' WHERE oer_code='P1699' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module SMARTRA, Cle, Calculateur moteur' WHERE oer_code='P169A' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoides de changement, Corps de vanne, Calculateur de transmission' WHERE oer_code='P1700' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, Calculateur de transmission' WHERE oer_code='P1701' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, Reglage' WHERE oer_code='P1702' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, Calculateur de transmission' WHERE oer_code='P1703' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, Calculateur de transmission' WHERE oer_code='P1704' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur inhibiteur, Cablage, Calculateur de transmission' WHERE oer_code='P1706' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Contacteur de frein, Cablage, Calculateur moteur' WHERE oer_code='P1707' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur, Cablage, Calculateur de transmission' WHERE oer_code='P1708' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur, Cablage, Calculateur de transmission' WHERE oer_code='P1709' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur de transmission' WHERE oer_code='P1710' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur de transmission' WHERE oer_code='P1711' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur de transmission' WHERE oer_code='P1712' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Calculateur de transmission' WHERE oer_code='P1713' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur, Capteur TPS, Cablage' WHERE oer_code='P1714' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur A/C, Cablage, Calculateur de transmission' WHERE oer_code='P1715' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''angle de direction, Cablage, Calculateur' WHERE oer_code='P1716' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''angle de direction, Cablage' WHERE oer_code='P1717' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''angle de direction, Cablage' WHERE oer_code='P1718' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur d''angle de direction, Cablage' WHERE oer_code='P1719' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Fusible, Cablage' WHERE oer_code='P1721' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur de transmission' WHERE oer_code='P1722' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, TCM' WHERE oer_code='P1723' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Fusible' WHERE oer_code='P1724' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module TOD, Cablage, Calculateur' WHERE oer_code='P1725' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS/APS, Cablage, TCM' WHERE oer_code='P1726' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, TCM' WHERE oer_code='P1727' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='EMC, Cablage, TCM' WHERE oer_code='P1728' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='EMC, Cablage, TCM' WHERE oer_code='P1729' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur de transmission' WHERE oer_code='P1730' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur de transmission' WHERE oer_code='P1731' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur de transmission' WHERE oer_code='P1732' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur de transmission' WHERE oer_code='P1733' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur de transmission' WHERE oer_code='P1734' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, Cablage, Calculateur de transmission' WHERE oer_code='P1735' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur, Cablage, TCM' WHERE oer_code='P1736' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur, Cablage, TCM' WHERE oer_code='P1737' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Moteur de changement, Solenoides, TCM' WHERE oer_code='P1738' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Codeur, Cablage, Calculateur de transmission' WHERE oer_code='P1739' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Codeur, Cablage, TCM' WHERE oer_code='P1740' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Codeur, Cablage, TCM' WHERE oer_code='P1741' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Codeur, Relais, Cablage' WHERE oer_code='P1742' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Codeur, Cablage, TCM' WHERE oer_code='P1743' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Convertisseur de couple, Solenoides, Corps de vanne, Transmission' WHERE oer_code='P1744' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, TCM, Module 4WD' WHERE oer_code='P1745' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Connecteur de diagnostic, TCM' WHERE oer_code='P1746' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, TCM, Calculateur moteur' WHERE oer_code='P1747' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, TCM, Calculateur moteur' WHERE oer_code='P1748' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, TCM, Calculateur moteur' WHERE oer_code='P1749' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Capteur de vitesse de roue, Cablage' WHERE oer_code='P1750' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Capteur de vitesse, Cablage' WHERE oer_code='P1751' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Capteur de vitesse, Cablage' WHERE oer_code='P1752' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Capteur de vitesse, Cablage' WHERE oer_code='P1753' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Cablage, Combiné d''instruments' WHERE oer_code='P1754' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, EMC, Cablage' WHERE oer_code='P1755' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, EMC, Cablage' WHERE oer_code='P1756' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, EMC, Cablage' WHERE oer_code='P1757' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Temoin, Cablage, Combine d''instruments' WHERE oer_code='P1758' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur de transmission' WHERE oer_code='P1759' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur de transmission, Solenoides' WHERE oer_code='P1760' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur de transmission, Batterie' WHERE oer_code='P1761' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur de transmission' WHERE oer_code='P1762' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur de transmission' WHERE oer_code='P1763' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, TCM' WHERE oer_code='P1764' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, TCM, Calculateur moteur' WHERE oer_code='P1765' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, TCM, Calculateur moteur' WHERE oer_code='P1766' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Module ABS, Cablage' WHERE oer_code='P1767' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pneus, Capteur de vitesse, TCM' WHERE oer_code='P1769' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de vitesse, EMC, TCM' WHERE oer_code='P1770' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='EMC, TCM' WHERE oer_code='P1771' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, TCM' WHERE oer_code='P1773' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Solenoide, TCM' WHERE oer_code='P1774' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='TCM, Cablage' WHERE oer_code='P1775' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module, Pompe a huile, Cablage' WHERE oer_code='P1776' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module, Pompe a huile, Cablage' WHERE oer_code='P1777' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Electrovanne, Solenoide VFS, Cablage' WHERE oer_code='P1778' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Fusible' WHERE oer_code='P1779' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie, Alternateur, Cablage, TCM' WHERE oer_code='P1780' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie, Alternateur, Cablage, TCM' WHERE oer_code='P1781' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Contacteur, TCM' WHERE oer_code='P1782' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Bus CAN, Cablage, Module ABS' WHERE oer_code='P1783' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe EOP, Cablage, TCM' WHERE oer_code='P1784' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, TCM' WHERE oer_code='P1785' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur, Cablage, TCM' WHERE oer_code='P1786' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Corps de vanne, Capteur de levier, TCM' WHERE oer_code='P1787' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur TPS, Cablage, TCM' WHERE oer_code='P1791' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Interrupteur, Cablage, TCM' WHERE oer_code='P1795' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur DCT, Procedure de calibration' WHERE oer_code='P17C0' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Actionneur d''embrayage, Cablage, Calculateur DCT' WHERE oer_code='P17C1' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Actionneur d''embrayage, Cablage, Calculateur DCT' WHERE oer_code='P17C2' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Transpondeur, Module immobiliseur, TCM' WHERE oer_code='P1801' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Antenne, Cablage, Module immobiliseur' WHERE oer_code='P1802' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur moteur, Module immobiliseur, Cablage' WHERE oer_code='P1803' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module immobiliseur, Calculateur moteur' WHERE oer_code='P1805' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de position d''embrayage, Cablage, TCM' WHERE oer_code='P1807' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de position d''embrayage, Cablage, TCM' WHERE oer_code='P1808' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module ESP, Bus CAN, Calculateur moteur' WHERE oer_code='P1811' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module ESP, Cablage, Calculateur moteur' WHERE oer_code='P1815' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe 4WD, Cablage, Module 4WD' WHERE oer_code='P1820' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Pompe 4WD, Fusible' WHERE oer_code='P1821' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Pompe 4WD, Connecteur' WHERE oer_code='P1822' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cablage, Pompe 4WD, Connecteur' WHERE oer_code='P1823' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Pompe 4WD, Systeme de refroidissement' WHERE oer_code='P1824' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, Cablage, Module 4WD' WHERE oer_code='P1825' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, Cablage, Module 4WD' WHERE oer_code='P1826' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, Cablage, Module 4WD' WHERE oer_code='P1827' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, Cablage, Module 4WD' WHERE oer_code='P1828' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Embrayage, Actionneur, Calculateur de transmission' WHERE oer_code='P1829' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Embrayage, Actionneur, Calculateur de transmission' WHERE oer_code='P1830' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Embrayage, Systeme de refroidissement, Calculateur de transmission' WHERE oer_code='P1831' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Embrayage, Systeme de refroidissement, Calculateur de transmission' WHERE oer_code='P1832' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Actionneur d''embrayage, Cablage, Calculateur de transmission' WHERE oer_code='P1833' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Actionneur d''embrayage, Calculateur de transmission' WHERE oer_code='P1834' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de pression, Cablage, Module 4WD' WHERE oer_code='P1835' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit hydraulique, Solenoides, Calculateur de transmission' WHERE oer_code='P1836' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Calculateur de transmission, Configuration logicielle' WHERE oer_code='P1837' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Actionneur d''embrayage, Cablage, Calculateur de transmission' WHERE oer_code='P1900' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur de transmission' WHERE oer_code='P1925' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Solenoide, Cablage, Calculateur de transmission' WHERE oer_code='P1929' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Cablage, Calculateur de transmission' WHERE oer_code='P1986' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module airbag, Cablage, Module hybride' WHERE oer_code='P1A6F' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module airbag, Cablage, Module hybride' WHERE oer_code='P1A71' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Courroie, Alternateur, Poulie' WHERE oer_code='P1A77' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie HV, Module BMS, Systeme de charge' WHERE oer_code='P1A86' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Convertisseur DC/DC, Circuit de refroidissement, Cablage' WHERE oer_code='P1A88' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de courant, Convertisseur DC/DC, Cablage' WHERE oer_code='P1A89' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature, Batterie auxiliaire, Cablage' WHERE oer_code='P1B03' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module OPI, Cablage, Calculateur hybride' WHERE oer_code='P1B1D' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Contacteurs HV, Cablage HV, Module BMS' WHERE oer_code='P1B25' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de courant, Cablage HV, Module BMS' WHERE oer_code='P1B62' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur, Cablage, Module BMS' WHERE oer_code='P1B67' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie HV, Cellules de batterie, Module BMS' WHERE oer_code='P1B70' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie HV, Systeme de charge, Module BMS' WHERE oer_code='P1B71' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de tension, Cablage, Module BMS' WHERE oer_code='P1B74' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de courant, Cablage, Module BMS' WHERE oer_code='P1B75' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Contacteur HV, Cablage, Module BMS' WHERE oer_code='P1B76' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Circuit de precharge, Contacteur, Module BMS' WHERE oer_code='P1B77' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature, Cablage, Module BMS' WHERE oer_code='P1B78' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature, Cablage, Module BMS' WHERE oer_code='P1B79' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cellules de batterie, Module BMS, Batterie HV' WHERE oer_code='P1B84' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Batterie HV, Cellules, Module BMS' WHERE oer_code='P1B95' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de tension, Cablage, Module BMS' WHERE oer_code='P1B96' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de temperature, Cablage, Module BMS' WHERE oer_code='P1B97' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Relais, Ventilateur, Cablage, Module BMS' WHERE oer_code='P1BA0' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Ventilateur, Cablage, Module BMS' WHERE oer_code='P1BA1' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Module OPI, Cablage, Calculateur hybride' WHERE oer_code='P1C28' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur Hall, Module OPI, Cablage' WHERE oer_code='P1C2B' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cable de phase, Moteur electrique, Onduleur' WHERE oer_code='P1C64' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Cable de phase, Generateur, Onduleur' WHERE oer_code='P1C6A' AND oer_make='Hyundai';
UPDATE tp_odberror SET oer_carpartstext='Capteur de position du generateur, Cablage, Module hybride' WHERE oer_code='P1C76' AND oer_make='Hyundai';
COMMIT;